services:
  - type: web
    name: video-to-prompt-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: REPLICATE_API_TOKEN
        sync: false
